## Modules

In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

## Read in Data

In [40]:
data = pd.read_csv('train.csv')
#data.head()

## Transform Data

In [41]:
data=np.array(data)
m, n = data.shape
np.random.shuffle(data)

data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]
X_dev = X_dev / 255.

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]
X_train = X_train / 255.


## Create NN Functions

### Initialize Parameters

In [ ]:
def init_params():
    W1 = np.random.rand(10, 784) - 0.5
    b1 = np.random.rand(10,1) - 0.5
    W2 = np.random.rand(10, 10) - 0.5
    b2 = np.random.rand(10,1) - 0.5
    return W1, b1, W2, b2

### Forward Propagation

In [43]:
def ReLU(Z):
    return np.maximum(0, Z)

def softmax(Z):
    A = np.exp(Z) / sum(np.exp(Z))
    return A

def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

### Backwards Propagation

In [ ]:
def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def deriv_ReLU(Z):
    return Z > 0

def back_prop(Z1, A1, Z2, A2, W2, X, Y):
    m = Y.size
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2, 1)
    dZ1 = W2.T.dot(dZ2) * deriv_ReLU(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1, 1)
    return dW1, db1, dW2, db2

### Update Parameters

In [ ]:
def update_params( W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha*dW1
    b1 = b1 - alpha*np.reshape(db1, (10,1))
    W2 = W2 - alpha*dW2
    b2 = b2 - alpha*np.reshape(db2, (10,1))
    return W1, b1, W2, b2

### Gradient Descent

In [44]:
def get_predictions(A2):
    return np.argmax(A2,0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions==Y)/Y.size

def gradient_descent(X, Y, iterations, alpha):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = back_prop(Z1, A1, Z2, A2, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 50 ==0:
            print("iteration: ", i)
            print("Accuracy: ", get_accuracy(get_predictions(A2), Y))
    return W1, b1, W2, b2

## Run Training

In [45]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 200, .1)

iteration:  0
[6 3 6 ... 6 3 6] [1 5 8 ... 6 7 5]
Accuracy:  0.08004878048780488
iteration:  50
[1 3 3 ... 6 7 3] [1 5 8 ... 6 7 5]
Accuracy:  0.5167317073170732
iteration:  100
[1 3 3 ... 6 7 3] [1 5 8 ... 6 7 5]
Accuracy:  0.6730731707317074
iteration:  150
[1 3 3 ... 6 7 3] [1 5 8 ... 6 7 5]
Accuracy:  0.7414390243902439
